import type { CanvasValidationRule } from "./canvas-blocks";

export const canvasValidationRules = [
  {
    code: "WF_STRUCTURE_001_TRIGGER_REQUIRED",
    category: "structure",
    severity: "error",
    scope: "workflow",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Workflow must have a trigger node.",
  },
  {
    code: "WF_STRUCTURE_002_SINGLE_PRIMARY_TRIGGER",
    category: "structure",
    severity: "error",
    scope: "workflow",
    blocks: ["test_flow", "compile", "publish", "run", "sync"],
    message: "Guided Canvas mode supports a single primary trigger.",
  },
  {
    code: "WF_STRUCTURE_003_END_NODE_REQUIRED",
    category: "structure",
    severity: "error",
    scope: "workflow",
    blocks: ["test_flow", "compile", "publish", "run", "sync"],
    message: "Workflow must have an end node.",
  },
  {
    code: "WF_STRUCTURE_004_NO_DISCONNECTED_NODE",
    category: "structure",
    severity: "error",
    scope: "node",
    blocks: ["test_flow", "compile", "publish", "run", "sync"],
    message: "All runtime nodes must be reachable from the trigger.",
  },
  {
    code: "WF_STRUCTURE_005_EDGE_TARGET_EXISTS",
    category: "structure",
    severity: "error",
    scope: "edge",
    blocks: ["test_flow", "compile", "publish", "run", "sync"],
    message: "Edges must reference existing source and target nodes.",
  },
  {
    code: "WF_STRUCTURE_006_HANDLE_EXISTS",
    category: "structure",
    severity: "error",
    scope: "edge",
    blocks: ["test_flow", "compile", "publish", "run", "sync"],
    message: "Edges must reference existing source and target handles.",
  },
  {
    code: "WF_STRUCTURE_007_NO_UNSUPPORTED_CYCLE",
    category: "structure",
    severity: "error",
    scope: "workflow",
    blocks: ["test_flow", "compile", "publish", "run", "sync"],
    message: "Unsupported control-flow cycles are forbidden outside loop blocks.",
  },
  {
    code: "WF_STRUCTURE_008_ROUTER_FALLBACK_REQUIRED",
    category: "structure",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "Router and condition blocks should have a fallback branch.",
  },
  {
    code: "WF_STRUCTURE_009_LOOP_BODY_REQUIRED",
    category: "structure",
    severity: "error",
    scope: "node",
    blocks: ["test_flow", "compile", "publish", "run"],
    message: "Loop blocks must have a loop body and an after-loop path.",
  },
  {
    code: "WF_STRUCTURE_010_MERGE_INPUTS_REQUIRED",
    category: "structure",
    severity: "error",
    scope: "node",
    blocks: ["test_flow", "compile", "publish", "run"],
    message: "Merge blocks must have at least two incoming branch inputs.",
  },
  {
    code: "WF_SCHEMA_001_WORKFLOW_SCHEMA_INVALID",
    category: "schema",
    severity: "error",
    scope: "workflow",
    blocks: ["save", "test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Workflow DSL does not match the canonical Canvas schema.",
  },
  {
    code: "WF_SCHEMA_002_NODE_SCHEMA_INVALID",
    category: "schema",
    severity: "error",
    scope: "node",
    blocks: ["save", "test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Canvas node does not match the canonical node schema.",
  },
  {
    code: "WF_SCHEMA_003_EDGE_SCHEMA_INVALID",
    category: "schema",
    severity: "error",
    scope: "edge",
    blocks: ["save", "test_flow", "compile", "publish", "run", "sync"],
    message: "Canvas edge does not match the canonical edge schema.",
  },
  {
    code: "WF_SCHEMA_004_NODE_CONFIG_INVALID",
    category: "schema",
    severity: "error",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Node config does not match the module config schema.",
  },
  {
    code: "WF_SCHEMA_005_CONDITION_SCHEMA_INVALID",
    category: "schema",
    severity: "error",
    scope: "edge",
    blocks: ["test_flow", "compile", "publish", "run"],
    message: "Condition expression schema is invalid.",
  },
  {
    code: "WF_SCHEMA_006_BINDING_SCHEMA_INVALID",
    category: "schema",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Input binding schema is invalid.",
  },
  {
    code: "WF_TYPE_001_REQUIRED_INPUT_MISSING",
    category: "type_compatibility",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Required step input must have a binding or configured default.",
  },
  {
    code: "WF_TYPE_002_OUTPUT_NOT_FOUND",
    category: "type_compatibility",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Input binding references a missing source output.",
  },
  {
    code: "WF_TYPE_003_INPUT_NOT_FOUND",
    category: "type_compatibility",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Input binding references a missing target input.",
  },
  {
    code: "WF_TYPE_004_INCOMPATIBLE_TYPES",
    category: "type_compatibility",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Source output type is incompatible with target input type.",
  },
  {
    code: "WF_TYPE_005_NULLABLE_TO_REQUIRED_WITHOUT_FALLBACK",
    category: "type_compatibility",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Nullable source cannot feed a required input without fallback.",
  },
  {
    code: "WF_TYPE_006_ARRAY_TO_SCALAR_WITHOUT_TRANSFORM",
    category: "type_compatibility",
    severity: "error",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Array source must declare selection or transform for scalar input.",
  },
  {
    code: "WF_TYPE_007_ENUM_VALUE_INVALID",
    category: "type_compatibility",
    severity: "error",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Configured enum value is not allowed.",
  },
  {
    code: "WF_LEGAL_001_CLAIM_DRAFT_REQUIRES_FACTS",
    category: "semantic",
    severity: "error",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Claim drafting modules require facts.",
  },
  {
    code: "WF_LEGAL_002_PRETRIAL_CLAIM_REQUIRES_COUNTERPARTY",
    category: "semantic",
    severity: "error",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Pretrial claim drafting requires a counterparty.",
  },
  {
    code: "WF_LEGAL_003_DOCUMENT_TEMPLATE_REQUIRED",
    category: "semantic",
    severity: "error",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Document drafting or template application requires a template.",
  },
  {
    code: "WF_LEGAL_004_CASE_LAW_SEARCH_RESULT_NOT_SELECTED",
    category: "semantic",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "Case law search results should be selected before drafting.",
  },
  {
    code: "WF_LEGAL_005_PROFILE_REQUIRED_FOR_PERSONALIZED_DRAFT",
    category: "semantic",
    severity: "error",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run"],
    message: "Personalized legal drafting requires a profile.",
  },
  {
    code: "WF_LEGAL_006_LEGAL_SOURCE_CITATION_REQUIRED_FOR_RAG_OUTPUT",
    category: "semantic",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "RAG-generated legal outputs should expose citations.",
  },
  {
    code: "WF_POLICY_001_EXTERNAL_ACTION_REQUIRES_APPROVAL",
    category: "policy",
    severity: "policy_block",
    scope: "node",
    blocks: ["publish", "run", "sync"],
    message: "External delivery requires an approval gate before execution.",
  },
  {
    code: "WF_POLICY_002_AI_ROUTE_FORBIDDEN_FOR_DATA_CLASS",
    category: "policy",
    severity: "policy_block",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "AI route is forbidden for this data classification.",
  },
  {
    code: "WF_POLICY_003_DOCUMENT_ACCESS_DENIED",
    category: "security",
    severity: "policy_block",
    scope: "binding",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Document reference is not accessible in the active workspace.",
  },
  {
    code: "WF_POLICY_004_CROSS_WORKSPACE_REFERENCE",
    category: "security",
    severity: "policy_block",
    scope: "binding",
    blocks: ["save", "test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Canvas workflow cannot reference another workspace.",
  },
  {
    code: "WF_POLICY_005_SECRET_VALUE_IN_CONFIG",
    category: "security",
    severity: "policy_block",
    scope: "node",
    blocks: ["save", "test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Secrets must not be stored directly in node config.",
  },
  {
    code: "WF_POLICY_006_DIRECT_SUPABASE_SERVICE_ROLE_FORBIDDEN",
    category: "security",
    severity: "policy_block",
    scope: "node",
    blocks: ["save", "test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Supabase service role values are forbidden in Canvas DSL.",
  },
  {
    code: "WF_POLICY_007_UNKNOWN_HTTP_DOMAIN",
    category: "security",
    severity: "policy_block",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "HTTP actions cannot call an unknown domain.",
  },
  {
    code: "WF_POLICY_008_CODE_STEP_FORBIDDEN",
    category: "security",
    severity: "policy_block",
    scope: "node",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Code steps are forbidden outside explicit admin review.",
  },
  {
    code: "WF_POLICY_009_PUBLISHED_TEMPLATE_HAS_PRIVATE_REFERENCE",
    category: "policy",
    severity: "policy_block",
    scope: "workflow",
    blocks: ["publish", "sync"],
    message: "Published templates cannot retain private document references.",
  },
  {
    code: "WF_POLICY_010_SIGNED_URL_IN_CONFIG_FORBIDDEN",
    category: "security",
    severity: "policy_block",
    scope: "node",
    blocks: ["save", "test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Signed URLs must not be persisted in Canvas config.",
  },
  {
    code: "WF_RUNTIME_001_RUNTIME_MAPPING_MISSING",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["compile", "publish", "run", "sync"],
    message: "Runtime mapping is missing.",
  },
  {
    code: "WF_RUNTIME_002_ACTIVEPIECES_PIECE_MISSING",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["compile", "publish", "run", "sync"],
    message: "Activepieces piece is not available.",
  },
  {
    code: "WF_RUNTIME_003_ACTIVEPIECES_ACTION_MISSING",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["compile", "publish", "run", "sync"],
    message: "Activepieces action is not available.",
  },
  {
    code: "WF_RUNTIME_004_CONNECTION_REQUIRED",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Runtime connection is required.",
  },
  {
    code: "WF_RUNTIME_005_CONNECTION_MISSING",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Runtime connection is missing.",
  },
  {
    code: "WF_RUNTIME_006_CONNECTION_ERROR",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["test_step", "test_flow", "compile", "publish", "run", "sync"],
    message: "Runtime connection is unavailable.",
  },
  {
    code: "WF_RUNTIME_007_RUNTIME_UNAVAILABLE",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["compile", "publish", "run", "sync"],
    message: "Runtime service is unavailable.",
  },
  {
    code: "WF_RUNTIME_008_COMPILER_UNSUPPORTED_NODE",
    category: "runtime",
    severity: "error",
    scope: "runtime",
    blocks: ["compile", "publish", "run", "sync"],
    message: "Compiler does not support this node.",
  },
  {
    code: "WF_RUNTIME_009_REVERSE_SYNC_UNKNOWN_STEP",
    category: "runtime",
    severity: "policy_block",
    scope: "runtime",
    blocks: ["save", "compile", "publish", "run", "sync"],
    message: "Reverse sync contains an unknown runtime step.",
  },
  {
    code: "WF_UX_001_DISPLAY_NAME_MISSING",
    category: "ux",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "Canvas node should have a readable display name.",
  },
  {
    code: "WF_UX_002_BRANCH_LABEL_MISSING",
    category: "ux",
    severity: "warning",
    scope: "edge",
    blocks: [],
    message: "Branch edge should have a readable label.",
  },
  {
    code: "WF_UX_003_APPROVAL_REASON_MISSING",
    category: "ux",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "Approval step should explain why review is required.",
  },
  {
    code: "WF_UX_004_END_RESULT_DESCRIPTION_MISSING",
    category: "ux",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "End step should describe the result.",
  },
  {
    code: "WF_UX_005_RISK_BADGE_REQUIRED",
    category: "ux",
    severity: "warning",
    scope: "node",
    blocks: [],
    message: "High-risk steps should expose a risk badge.",
  },
] as const satisfies readonly CanvasValidationRule[];

export type CanvasValidationRuleCode =
  (typeof canvasValidationRules)[number]["code"];

export function findCanvasValidationRule(code: string) {
  return canvasValidationRules.find((rule) => rule.code === code) ?? null;
}
