import type {
  CanvasDataVisibilityMode,
  CanvasOperationType,
  CanvasRiskLevel,
  CanvasSecurityResourceType,
} from '@lexframe/contracts';
import type { PermissionCode } from '@lexframe/contracts';

export interface CanvasOperationPolicy {
  readonly action: string;
  readonly resource: CanvasSecurityResourceType;
  readonly requiredPermissions: readonly PermissionCode[];
  readonly riskLevel: CanvasRiskLevel;
  readonly redactionMode: CanvasDataVisibilityMode;
  readonly auditEvent: string;
  readonly reauthRequired?: boolean;
  readonly policyValidationRequired?: boolean;
}

export const CANVAS_OPERATION_POLICY_MAP: Record<
  CanvasOperationType,
  CanvasOperationPolicy
> = {
  ADD_NODE_FROM_MODULE: {
    action: 'canvas.operation.add_node_from_module',
    resource: 'node',
    requiredPermissions: ['canvas.add_node'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.graph.node.added',
    policyValidationRequired: true,
  },
  ADD_NODE: {
    action: 'canvas.operation.add_node',
    resource: 'node',
    requiredPermissions: ['canvas.add_node'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.graph.node.added',
    policyValidationRequired: true,
  },
  DUPLICATE_NODE: {
    action: 'canvas.operation.duplicate_node',
    resource: 'node',
    requiredPermissions: ['canvas.add_node', 'canvas.edit_node_config'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.graph.node.duplicated',
    policyValidationRequired: true,
  },
  UPDATE_NODE: {
    action: 'canvas.operation.update_node',
    resource: 'node',
    requiredPermissions: ['canvas.edit_node_config'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.graph.node.updated',
    policyValidationRequired: true,
  },
  MOVE_NODE: {
    action: 'canvas.operation.move_node',
    resource: 'node',
    requiredPermissions: ['canvas.edit_layout'],
    riskLevel: 'low',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.graph.layout.updated',
  },
  DELETE_NODE: {
    action: 'canvas.operation.delete_node',
    resource: 'node',
    requiredPermissions: ['canvas.delete_node'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.graph.node.deleted',
    policyValidationRequired: true,
  },
  ADD_EDGE: {
    action: 'canvas.operation.add_edge',
    resource: 'edge',
    requiredPermissions: ['canvas.add_edge'],
    riskLevel: 'medium',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.graph.edge.added',
    policyValidationRequired: true,
  },
  DELETE_EDGE: {
    action: 'canvas.operation.delete_edge',
    resource: 'edge',
    requiredPermissions: ['canvas.delete_edge'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.graph.edge.deleted',
    policyValidationRequired: true,
  },
  UPDATE_EDGE: {
    action: 'canvas.operation.update_edge',
    resource: 'edge',
    requiredPermissions: ['canvas.edit_conditions'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.graph.edge.updated',
    policyValidationRequired: true,
  },
  UPDATE_NODE_CONFIG: {
    action: 'canvas.operation.update_node_config',
    resource: 'node',
    requiredPermissions: ['canvas.edit_node_config'],
    riskLevel: 'high',
    redactionMode: 'redacted',
    auditEvent: 'canvas.graph.node_config.updated',
    policyValidationRequired: true,
  },
  UPDATE_LAYOUT: {
    action: 'canvas.operation.update_layout',
    resource: 'draft',
    requiredPermissions: ['canvas.edit_layout'],
    riskLevel: 'low',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.graph.layout.updated',
  },
  UPSERT_WORKFLOW_INPUT: {
    action: 'canvas.operation.upsert_workflow_input',
    resource: 'draft',
    requiredPermissions: ['canvas.edit_bindings'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.bindings.workflow_input.upserted',
    policyValidationRequired: true,
  },
  DELETE_WORKFLOW_INPUT: {
    action: 'canvas.operation.delete_workflow_input',
    resource: 'draft',
    requiredPermissions: ['canvas.edit_bindings'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.bindings.workflow_input.deleted',
    policyValidationRequired: true,
  },
  UPSERT_WORKFLOW_OUTPUT: {
    action: 'canvas.operation.upsert_workflow_output',
    resource: 'draft',
    requiredPermissions: ['canvas.edit_bindings'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.bindings.workflow_output.upserted',
    policyValidationRequired: true,
  },
  DELETE_WORKFLOW_OUTPUT: {
    action: 'canvas.operation.delete_workflow_output',
    resource: 'draft',
    requiredPermissions: ['canvas.edit_bindings'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.bindings.workflow_output.deleted',
    policyValidationRequired: true,
  },
  UPSERT_INPUT_BINDING: {
    action: 'canvas.operation.upsert_input_binding',
    resource: 'binding',
    requiredPermissions: ['canvas.edit_bindings'],
    riskLevel: 'high',
    redactionMode: 'redacted',
    auditEvent: 'canvas.bindings.input.upserted',
    policyValidationRequired: true,
  },
  DELETE_INPUT_BINDING: {
    action: 'canvas.operation.delete_input_binding',
    resource: 'binding',
    requiredPermissions: ['canvas.edit_bindings'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.bindings.input.deleted',
    policyValidationRequired: true,
  },
  PIN_SAMPLE_DATA: {
    action: 'canvas.operation.pin_sample_data',
    resource: 'test_run',
    requiredPermissions: ['canvas.test.pin_data'],
    riskLevel: 'high',
    redactionMode: 'redacted',
    auditEvent: 'canvas.testing.sample_data.pinned',
    reauthRequired: true,
  },
  UNPIN_SAMPLE_DATA: {
    action: 'canvas.operation.unpin_sample_data',
    resource: 'test_run',
    requiredPermissions: ['canvas.test.pin_data'],
    riskLevel: 'medium',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.testing.sample_data.unpinned',
  },
  UPDATE_CONDITION: {
    action: 'canvas.operation.update_condition',
    resource: 'condition',
    requiredPermissions: ['canvas.edit_conditions'],
    riskLevel: 'high',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.conditions.updated',
    policyValidationRequired: true,
  },
  UPDATE_WORKFLOW_POLICY: {
    action: 'canvas.operation.update_workflow_policy',
    resource: 'policy',
    requiredPermissions: ['canvas.policy_override'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.policy.workflow.updated',
    reauthRequired: true,
    policyValidationRequired: true,
  },
  UPDATE_NODE_POLICY: {
    action: 'canvas.operation.update_node_policy',
    resource: 'policy',
    requiredPermissions: ['canvas.edit_node_config', 'canvas.policy_override'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.policy.node.updated',
    reauthRequired: true,
    policyValidationRequired: true,
  },
  SNAPSHOT_RESTORE: {
    action: 'canvas.operation.snapshot_restore',
    resource: 'draft',
    requiredPermissions: ['canvas.version.restore_as_draft'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.lifecycle.snapshot_restored',
    reauthRequired: true,
  },
  RUNTIME_IMPORT_AS_DRAFT: {
    action: 'canvas.operation.runtime_import_as_draft',
    resource: 'runtime',
    requiredPermissions: [
      'canvas.runtime.import_apply',
      'canvas.security_review',
    ],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.runtime.import_applied',
    reauthRequired: true,
    policyValidationRequired: true,
  },
};

export const CANVAS_ENDPOINT_POLICY_MAP = {
  'compile-preview': {
    action: 'canvas.compile.preview',
    resource: 'runtime',
    requiredPermissions: ['canvas.view_compile_preview'],
    riskLevel: 'medium',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.runtime.compile_preview.viewed',
  },
  compile: {
    action: 'canvas.compile',
    resource: 'runtime',
    requiredPermissions: ['canvas.compile'],
    riskLevel: 'high',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.runtime.compiled',
  },
  'sync-runtime': {
    action: 'canvas.runtime.sync',
    resource: 'runtime',
    requiredPermissions: ['canvas.sync_runtime'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.runtime.synced',
    reauthRequired: true,
  },
  publish: {
    action: 'canvas.publish',
    resource: 'version',
    requiredPermissions: ['canvas.publish'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.version.publish_requested',
    reauthRequired: true,
  },
  rollback: {
    action: 'canvas.version.rollback',
    resource: 'version',
    requiredPermissions: ['canvas.version.rollback'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.version.rollback_requested',
    reauthRequired: true,
  },
  'emergency-disable': {
    action: 'canvas.version.emergency_disable',
    resource: 'version',
    requiredPermissions: ['canvas.version.emergency_disable'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.version.emergency_disable_requested',
    reauthRequired: true,
  },
  'runtime-pull': {
    action: 'canvas.runtime.pull',
    resource: 'runtime',
    requiredPermissions: ['canvas.runtime.pull'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.runtime.snapshot_pulled',
  },
  'runtime-import-preview': {
    action: 'canvas.runtime.import_preview',
    resource: 'runtime',
    requiredPermissions: ['canvas.runtime.import_preview'],
    riskLevel: 'high',
    redactionMode: 'structured_safe',
    auditEvent: 'canvas.runtime.import_previewed',
  },
  'runtime-import-apply': {
    action: 'canvas.runtime.import_apply',
    resource: 'runtime',
    requiredPermissions: [
      'canvas.runtime.import_apply',
      'canvas.security_review',
    ],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.runtime.import_applied',
    reauthRequired: true,
  },
  'runtime-import-reject': {
    action: 'canvas.runtime.import_reject',
    resource: 'runtime',
    requiredPermissions: ['canvas.runtime.reject_import'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.runtime.import_rejected',
  },
  'runtime-overwrite': {
    action: 'canvas.runtime.overwrite',
    resource: 'runtime',
    requiredPermissions: ['canvas.runtime.overwrite'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.runtime.overwritten',
    reauthRequired: true,
  },
  'advanced-builder': {
    action: 'canvas.advanced_builder.open',
    resource: 'runtime',
    requiredPermissions: ['canvas.open_advanced_builder'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.advanced_builder.opened',
    reauthRequired: true,
  },
  'audit-read': {
    action: 'canvas.audit.read',
    resource: 'audit_event',
    requiredPermissions: ['canvas.audit_read'],
    riskLevel: 'high',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.audit.read',
  },
  'audit-export': {
    action: 'canvas.audit.export',
    resource: 'audit_event',
    requiredPermissions: ['canvas.audit_export'],
    riskLevel: 'critical',
    redactionMode: 'metadata_only',
    auditEvent: 'canvas.audit.exported',
    reauthRequired: true,
  },
} satisfies Record<string, CanvasOperationPolicy>;

export type CanvasEndpointPolicyKey = keyof typeof CANVAS_ENDPOINT_POLICY_MAP;
