export const permissionCodes = [
  "dashboard.view",
  "workspace.read",
  "workspace.update",
  "workspace.switch",
  "workspace.invite",
  "workspace.member.read",
  "workspace.member.update_role",
  "workspace.member.remove",
  "workspace.security.read",
  "workspace.security.manage",
  "session.read",
  "session.revoke",
  "profile.read",
  "profile.update",
  "profile.publish",
  "profile.override_personal",
  "document.read",
  "document.upload",
  "document.generate",
  "document.delete",
  "document.restore",
  "document.template.read",
  "document.template.publish",
  "document.template.map_fields",
  "document.template.manage",
  "document.validation.read",
  "document.validation.resolve",
  "legal_sources.manage",
  "module.manage",
  "legal_search.use",
  "automation.read",
  "automation.install",
  "automation.edit",
  "automation.fork",
  "automation.update_source",
  "automation.approve_external",
  "automation.publish",
  "automation.submit_publication",
  "automation.run",
  "ai.chat.use",
  "ai.workflow.create",
  "ai.workflow.patch",
  "ai.policy.read",
  "ai.policy.manage",
  "legal_rag.use",
  "ai.use_confidential",
  "ai.use_legal_secret",
  "ai.admin.playground",
  "activepieces.open_builder",
  "activepieces.sync_flow",
  "approval.route.manage",
  "approval.task.read",
  "approval.task.decide",
  "connections.manage",
  "moderation.review",
  "recommendation.read",
  "recommendation.accept",
  "recommendation.manage",
  "secret.read_metadata",
  "secret.rotate",
  "billing.read",
  "billing.manage",
  "audit.read",
  "audit.export",
  "incident.read",
  "incident.manage",
  "compliance.read",
  "compliance.manage",
  "access_review.manage",
  "support.bundle.create",
] as const;

export type PermissionCode = (typeof permissionCodes)[number];

export const roleCodes = [
  "owner",
  "admin",
  "lawyer",
  "assistant",
  "viewer",
  "security_admin",
  "billing_admin",
] as const;

export type RoleCode = (typeof roleCodes)[number];
