export * from "./ai";
export * from "./canvas";
export * from "./canvas-ai";
export * from "./domain";
export * from "./legal";
export * from "./stage7";
export * from "./stage8";
export * from "./stage15";
export * from "./stage12";
export * from "./enums/data-classification";
export * from "./errors/error-codes";
export * from "./events/event-catalog";
export * from "./permissions/permission-codes";
export * from "./fixtures/demo-data";
export * from "./fixtures/ai-fixtures";
export * from "./fixtures/legal-fixtures";
export * from "./fixtures/recommendation-fixtures";
export * from "./fixtures/stage15-fixtures";

import workflowSchemaJson from "./workflow/workflow.schema.json";
import workflowPatchSchemaJson from "./workflow/workflow-patch.schema.json";
import releaseManifestSchemaJson from "./release/release-manifest.schema.json";
import canvasWorkflowV2SchemaJson from "./canvas/workflow-v2.schema.json";
import canvasNodeSchemaJson from "./canvas/node.schema.json";
import canvasEdgeSchemaJson from "./canvas/edge.schema.json";
import canvasBindingSchemaJson from "./canvas/binding.schema.json";
import canvasConditionSchemaJson from "./canvas/condition.schema.json";
import canvasOperationSchemaJson from "./canvas/operation.schema.json";
import canvasPinnedDataSchemaJson from "./canvas/pinned-data.schema.json";
import canvasPolicySchemaJson from "./canvas/policy.schema.json";
import canvasRuntimeProjectionSchemaJson from "./canvas/runtime-projection.schema.json";
import canvasSampleDataSchemaJson from "./canvas/sample-data.schema.json";
import canvasValidationSchemaJson from "./canvas/validation.schema.json";
import canvasAiMessageSchemaJson from "./canvas/canvas-ai-message.schema.json";
import canvasAiPatchProposalSchemaJson from "./canvas/canvas-ai-patch-proposal.schema.json";
import canvasAiStructuredOutputSchemaJson from "./canvas/canvas-ai-structured-output.schema.json";
import localOwnerKeysSchemaJson from "./local-owner-key-vault/local-owner-keys.schema.json";

export const workflowSchema = workflowSchemaJson;
export const workflowPatchSchema = workflowPatchSchemaJson;
export const releaseManifestSchema = releaseManifestSchemaJson;
export const canvasWorkflowV2Schema = canvasWorkflowV2SchemaJson;
export const canvasNodeSchema = canvasNodeSchemaJson;
export const canvasEdgeSchema = canvasEdgeSchemaJson;
export const canvasBindingSchema = canvasBindingSchemaJson;
export const canvasConditionSchema = canvasConditionSchemaJson;
export const canvasOperationSchema = canvasOperationSchemaJson;
export const canvasPinnedDataSchema = canvasPinnedDataSchemaJson;
export const canvasPolicySchema = canvasPolicySchemaJson;
export const canvasRuntimeProjectionSchema = canvasRuntimeProjectionSchemaJson;
export const canvasSampleDataSchema = canvasSampleDataSchemaJson;
export const canvasValidationSchema = canvasValidationSchemaJson;
export const canvasAiMessageSchema = canvasAiMessageSchemaJson;
export const canvasAiPatchProposalSchema = canvasAiPatchProposalSchemaJson;
export const canvasAiStructuredOutputSchema = canvasAiStructuredOutputSchemaJson;
export const localOwnerKeysSchema = localOwnerKeysSchemaJson;
