import type { DataClassification } from "../enums/data-classification";

export type EventOwner =
  | "frontend"
  | "backend"
  | "workflow_runtime"
  | "analytics";

export type EventGroup =
  | "session"
  | "search"
  | "document"
  | "delivery"
  | "library"
  | "workflow"
  | "canvas"
  | "profile"
  | "approval"
  | "notification"
  | "recommendation";

export type EventRiskLevel = "low" | "medium" | "high";

export type EventPrivacyClass = DataClassification | "legal_secret";

export interface EventDefinition {
  readonly event: string;
  readonly owner: EventOwner;
  readonly eventGroup: EventGroup;
  readonly schemaVersion: "lexframe.product-event.v1";
  readonly description: string;
  readonly activityCode: string;
  readonly isRecommendationSignal: boolean;
  readonly isAuthoritative: boolean;
  readonly riskLevel: EventRiskLevel;
  readonly allowedSources: readonly EventOwner[];
  readonly privacyClass: EventPrivacyClass;
  readonly requiredFields: readonly string[];
  readonly payloadSchema: Record<string, unknown>;
  readonly denylistFields: readonly string[];
  readonly deprecatedAt: string | null;
}

export const eventPayloadDenylist = [
  "accessToken",
  "refreshToken",
  "password",
  "secret",
  "rawText",
  "body",
  "contentText",
  "recipientEmails",
  "phone",
  "passport",
  "inn",
  "snils",
] as const;

function defineEvent(
  input: Omit<
    EventDefinition,
    "schemaVersion" | "denylistFields" | "deprecatedAt" | "payloadSchema"
  > & {
    readonly payloadProperties?: Record<string, unknown>;
    readonly denylistFields?: readonly string[];
    readonly deprecatedAt?: string | null;
  },
): EventDefinition {
  return {
    ...input,
    schemaVersion: "lexframe.product-event.v1",
    payloadSchema: {
      type: "object",
      additionalProperties: true,
      required: input.requiredFields,
      properties: input.payloadProperties ?? {},
    },
    denylistFields: input.denylistFields ?? eventPayloadDenylist,
    deprecatedAt: input.deprecatedAt ?? null,
  };
}

export const eventCatalog: readonly EventDefinition[] = [
  defineEvent({
    event: "session.context.loaded",
    owner: "backend",
    eventGroup: "session",
    description: "Session context resolved after Supabase identity exchange.",
    activityCode: "session.context.loaded",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "actorId", "roles"],
  }),
  defineEvent({
    event: "library.template.installed",
    owner: "backend",
    eventGroup: "library",
    description: "A product template was installed into a workspace.",
    activityCode: "library.template.installed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "templateId", "installedAutomationId"],
  }),
  defineEvent({
    event: "library.template.viewed",
    owner: "frontend",
    eventGroup: "library",
    description: "A user opened a template detail screen in the library.",
    activityCode: "library.template.viewed",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "templateId", "scope"],
  }),
  defineEvent({
    event: "library.template.install_failed",
    owner: "backend",
    eventGroup: "library",
    description: "Template installation failed before runtime sync.",
    activityCode: "library.template.install_failed",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "templateId", "errorCode"],
  }),
  defineEvent({
    event: "library.template.forked",
    owner: "backend",
    eventGroup: "library",
    description:
      "An installed automation or template was forked into a draft template.",
    activityCode: "library.template.forked",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "templateId", "forkTemplateId"],
  }),
  defineEvent({
    event: "library.publication.submitted",
    owner: "backend",
    eventGroup: "library",
    description: "A workspace template was submitted for moderation.",
    activityCode: "library.publication.submitted",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "templateId", "publicationRequestId"],
  }),
  defineEvent({
    event: "library.publication.reviewed",
    owner: "backend",
    eventGroup: "library",
    description:
      "A moderator approved, rejected, or requested changes for a publication request.",
    activityCode: "library.publication.reviewed",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "publicationRequestId", "decision"],
  }),
  defineEvent({
    event: "workflow.run.started",
    owner: "workflow_runtime",
    eventGroup: "workflow",
    description: "A LexFrame workflow run was requested and accepted.",
    activityCode: "workflow.run.started",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["workflow_runtime", "backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "runId", "automationVersionId"],
  }),
  defineEvent({
    event: "workflow.run.completed",
    owner: "workflow_runtime",
    eventGroup: "workflow",
    description: "A LexFrame workflow run completed with artifacts or outputs.",
    activityCode: "workflow.run.completed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["workflow_runtime", "backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "runId", "status", "durationMs"],
  }),
  defineEvent({
    event: "workflow.run.cancelled",
    owner: "backend",
    eventGroup: "workflow",
    description: "A user or system cancelled an execution run.",
    activityCode: "workflow.run.cancelled",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "runId", "actorUserId"],
  }),
  defineEvent({
    event: "canvas_palette_opened",
    owner: "frontend",
    eventGroup: "canvas",
    description: "A user opened the Canvas module palette.",
    activityCode: "canvas_palette_opened",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId"],
  }),
  defineEvent({
    event: "canvas_module_search_performed",
    owner: "frontend",
    eventGroup: "canvas",
    description: "A user searched the Canvas module catalog.",
    activityCode: "canvas_module_search_performed",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId"],
    denylistFields: ["documentText", "prompt", "aiOutput", "email", "clientName"],
  }),
  defineEvent({
    event: "canvas_module_detail_opened",
    owner: "frontend",
    eventGroup: "canvas",
    description: "A user opened a Canvas module detail drawer.",
    activityCode: "canvas_module_detail_opened",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "moduleCode"],
  }),
  defineEvent({
    event: "canvas_module_add_started",
    owner: "frontend",
    eventGroup: "canvas",
    description: "A user started adding a Canvas module.",
    activityCode: "canvas_module_add_started",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "moduleCode", "source"],
  }),
  defineEvent({
    event: "canvas_module_add_completed",
    owner: "backend",
    eventGroup: "canvas",
    description: "Backend accepted a Canvas module add operation.",
    activityCode: "canvas_module_add_completed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "moduleCode"],
  }),
  defineEvent({
    event: "canvas_module_add_failed",
    owner: "backend",
    eventGroup: "canvas",
    description: "Backend rejected a Canvas module add operation.",
    activityCode: "canvas_module_add_failed",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "moduleCode", "reasonCode"],
  }),
  defineEvent({
    event: "canvas_auto_binding_created",
    owner: "backend",
    eventGroup: "canvas",
    description: "Backend created an automatic input binding for a Canvas module.",
    activityCode: "canvas_auto_binding_created",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "moduleCode", "bindingId"],
  }),
  defineEvent({
    event: "canvas_auto_binding_suggested",
    owner: "backend",
    eventGroup: "canvas",
    description: "Backend suggested but did not apply an input binding.",
    activityCode: "canvas_auto_binding_suggested",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "moduleCode"],
  }),
  defineEvent({
    event: "canvas_ai.session_started",
    owner: "backend",
    eventGroup: "canvas",
    description: "A Canvas AI Assistant session started for a draft.",
    activityCode: "canvas_ai.session_started",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId"],
    denylistFields: [
      "rawDocumentText",
      "rawPrompt",
      "rawAiOutput",
      "prompt",
      "llmResponse",
      "email",
      "clientName",
      "signedUrl",
      "secret",
    ],
  }),
  defineEvent({
    event: "canvas_ai.message_submitted",
    owner: "backend",
    eventGroup: "canvas",
    description: "A user submitted a message to Canvas AI Assistant.",
    activityCode: "canvas_ai.message_submitted",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId", "mode"],
    denylistFields: [
      "rawDocumentText",
      "rawPrompt",
      "rawAiOutput",
      "prompt",
      "llmResponse",
      "email",
      "clientName",
      "signedUrl",
      "secret",
    ],
  }),
  defineEvent({
    event: "canvas_ai.context_built",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant built a redacted Canvas context.",
    activityCode: "canvas_ai.context_built",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId", "contextHash"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.tool_called",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant executed an allowlisted backend tool.",
    activityCode: "canvas_ai.tool_called",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId", "toolName"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.patch_proposed",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant proposed a CanvasOperation patch.",
    activityCode: "canvas_ai.patch_proposed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "patchId", "status"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.patch_validation_failed",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant patch failed Canvas validation.",
    activityCode: "canvas_ai.patch_validation_failed",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "patchId", "status"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.patch_policy_blocked",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant patch was blocked by policy.",
    activityCode: "canvas_ai.patch_policy_blocked",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "patchId", "policyCodes"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.patch_applied",
    owner: "backend",
    eventGroup: "canvas",
    description: "A confirmed Canvas AI Assistant patch was applied.",
    activityCode: "canvas_ai.patch_applied",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "patchId"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.patch_rejected",
    owner: "backend",
    eventGroup: "canvas",
    description: "A Canvas AI Assistant patch was rejected without draft changes.",
    activityCode: "canvas_ai.patch_rejected",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "patchId"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.clarification_requested",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant requested clarification before patching.",
    activityCode: "canvas_ai.clarification_requested",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.sensitive_context_redacted",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant redacted sensitive context before AI use.",
    activityCode: "canvas_ai.sensitive_context_redacted",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId", "redactionCodes"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.test_plan_generated",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant generated a non-production Canvas test plan.",
    activityCode: "canvas_ai.test_plan_generated",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "canvas_ai.debug_explanation_generated",
    owner: "backend",
    eventGroup: "canvas",
    description: "Canvas AI Assistant generated a redacted debug explanation.",
    activityCode: "canvas_ai.debug_explanation_generated",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "automationId", "sessionId"],
    denylistFields: ["rawDocumentText", "rawPrompt", "rawAiOutput", "secret"],
  }),
  defineEvent({
    event: "document.generated",
    owner: "backend",
    eventGroup: "document",
    description: "A document artifact was generated or attached to a run.",
    activityCode: "document.generated",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend", "workflow_runtime"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "documentId", "artifactId", "documentKind"],
  }),
  defineEvent({
    event: "profile.created",
    owner: "backend",
    eventGroup: "profile",
    description: "A legal work profile draft was created.",
    activityCode: "profile.created",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "profileId", "profileType"],
  }),
  defineEvent({
    event: "profile.published",
    owner: "backend",
    eventGroup: "profile",
    description: "A legal work profile version was published and frozen.",
    activityCode: "profile.published",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "profileId", "versionId"],
  }),
  defineEvent({
    event: "profile.snapshot.created",
    owner: "backend",
    eventGroup: "profile",
    description:
      "An effective profile snapshot was generated for preview or run execution.",
    activityCode: "profile.snapshot.created",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "snapshotId", "sourceProfileVersionIds"],
  }),
  defineEvent({
    event: "clause.updated",
    owner: "backend",
    eventGroup: "profile",
    description: "A clause library item or phrase rule was created or updated.",
    activityCode: "profile.clause.updated",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "clauseId", "scope"],
  }),
  defineEvent({
    event: "document.template.uploaded",
    owner: "backend",
    eventGroup: "document",
    description: "A DOCX template was registered in the canonical template library.",
    activityCode: "document.template.uploaded",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "templateId", "documentId"],
  }),
  defineEvent({
    event: "document.generation.previewed",
    owner: "backend",
    eventGroup: "document",
    description: "A document generation preview job completed.",
    activityCode: "document.generation.previewed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "generationJobId", "templateVersionId"],
  }),
  defineEvent({
    event: "document.validation.completed",
    owner: "backend",
    eventGroup: "document",
    description: "A validation report was computed for a generated document or preview.",
    activityCode: "document.validation.completed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "validationReportId", "status"],
  }),
  defineEvent({
    event: "approval.task.created",
    owner: "backend",
    eventGroup: "approval",
    description:
      "An approval task was created for external delivery or document finalization.",
    activityCode: "approval.task.created",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "approvalTaskId", "generationJobId"],
  }),
  defineEvent({
    event: "approval.task.approved",
    owner: "backend",
    eventGroup: "approval",
    description: "An approval task was approved by the assigned approver.",
    activityCode: "approval.task.approved",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "approvalTaskId", "approverId"],
  }),
  defineEvent({
    event: "approval.task.rejected",
    owner: "backend",
    eventGroup: "approval",
    description: "An approval task was rejected by the assigned approver.",
    activityCode: "approval.task.rejected",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "approvalTaskId", "approverId"],
  }),
  defineEvent({
    event: "approval.task.changes_requested",
    owner: "backend",
    eventGroup: "approval",
    description:
      "An approval task requested changes instead of approval or rejection.",
    activityCode: "approval.task.changes_requested",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "approvalTaskId", "approverId"],
  }),
  defineEvent({
    event: "delivery.request.created",
    owner: "backend",
    eventGroup: "delivery",
    description: "A delivery request was created from run output.",
    activityCode: "delivery.request.created",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "deliveryRequestId", "runId", "channel"],
  }),
  defineEvent({
    event: "delivery.request.approved",
    owner: "backend",
    eventGroup: "delivery",
    description: "A delivery request received explicit approval.",
    activityCode: "delivery.request.approved",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "deliveryRequestId", "approverId"],
  }),
  defineEvent({
    event: "delivery.request.sent",
    owner: "backend",
    eventGroup: "delivery",
    description: "A delivery request was sent through the configured adapter.",
    activityCode: "delivery.request.sent",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "deliveryRequestId", "attemptNo"],
  }),
  defineEvent({
    event: "notification.created",
    owner: "backend",
    eventGroup: "notification",
    description: "A workspace notification became visible in the execution inbox.",
    activityCode: "notification.created",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "notificationId", "type"],
  }),
  defineEvent({
    event: "document.finalized",
    owner: "backend",
    eventGroup: "document",
    description: "A generated document was finalized and persisted as canonical artifact.",
    activityCode: "document.finalized",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: [
      "workspaceId",
      "generationJobId",
      "documentId",
      "documentVersionId",
    ],
  }),
  defineEvent({
    event: "legal_search_performed",
    owner: "backend",
    eventGroup: "search",
    description: "A workspace-scoped legal search query completed.",
    activityCode: "search.query.completed",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "queryHash", "mode", "resultCount"],
  }),
  defineEvent({
    event: "legal_source_opened",
    owner: "frontend",
    eventGroup: "search",
    description: "A user opened a legal source detail or citation preview.",
    activityCode: "search.source.opened",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "sourceId", "visibility"],
  }),
  defineEvent({
    event: "legal_source_selected_for_workflow",
    owner: "frontend",
    eventGroup: "search",
    description:
      "A search result or source was added to the research basket for workflow use.",
    activityCode: "search.source.selected",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "sourceId", "selectionContext"],
  }),
  defineEvent({
    event: "legal_source_used_in_rag",
    owner: "backend",
    eventGroup: "search",
    description: "A legal source chunk was added into a RAG request context.",
    activityCode: "search.source.used_in_rag",
    isRecommendationSignal: true,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "ragRequestId", "sourceId", "chunkId"],
  }),
  defineEvent({
    event: "ai_route_blocked",
    owner: "backend",
    eventGroup: "search",
    description: "A legal RAG request was blocked by AI route policy.",
    activityCode: "search.ai_route_blocked",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "high",
    allowedSources: ["backend"],
    privacyClass: "confidential",
    requiredFields: ["workspaceId", "ragRequestId", "dataClass", "reasonCode"],
  }),
  defineEvent({
    event: "legal_search_feedback_submitted",
    owner: "frontend",
    eventGroup: "search",
    description:
      "A user submitted explicit relevance feedback for a legal search result.",
    activityCode: "search.feedback.submitted",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "queryId", "resultId", "feedbackType"],
  }),
  defineEvent({
    event: "recommendation.candidate.created",
    owner: "analytics",
    eventGroup: "recommendation",
    description: "A recommendation candidate became visible in the inbox.",
    activityCode: "recommendation.candidate.created",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["analytics", "backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "candidateId", "sourceTraceId"],
  }),
  defineEvent({
    event: "recommendation.opened",
    owner: "frontend",
    eventGroup: "recommendation",
    description: "A user opened a recommendation detail surface.",
    activityCode: "recommendation.opened",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "scope"],
  }),
  defineEvent({
    event: "recommendation.accept_requested",
    owner: "frontend",
    eventGroup: "recommendation",
    description: "A user requested conversion of a recommendation into a workflow draft.",
    activityCode: "recommendation.accept.requested",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "medium",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "scope"],
  }),
  defineEvent({
    event: "recommendation.dismiss_requested",
    owner: "frontend",
    eventGroup: "recommendation",
    description: "A user dismissed a recommendation candidate from the inbox.",
    activityCode: "recommendation.dismiss.requested",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "scope"],
  }),
  defineEvent({
    event: "recommendation.snooze_requested",
    owner: "frontend",
    eventGroup: "recommendation",
    description: "A user snoozed a recommendation candidate for later review.",
    activityCode: "recommendation.snooze.requested",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "scope"],
  }),
  defineEvent({
    event: "recommendation.feedback_submitted",
    owner: "frontend",
    eventGroup: "recommendation",
    description: "A user submitted recommendation feedback.",
    activityCode: "recommendation.feedback.submitted",
    isRecommendationSignal: true,
    isAuthoritative: false,
    riskLevel: "low",
    allowedSources: ["frontend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "feedbackType"],
  }),
  defineEvent({
    event: "recommendation.accepted",
    owner: "backend",
    eventGroup: "recommendation",
    description:
      "A recommendation was converted into a workflow draft without publishing or syncing it.",
    activityCode: "recommendation.accepted",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "medium",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "draftId"],
  }),
  defineEvent({
    event: "recommendation.dismissed",
    owner: "backend",
    eventGroup: "recommendation",
    description: "A recommendation candidate was dismissed by a user or policy.",
    activityCode: "recommendation.dismissed",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "actorUserId"],
  }),
  defineEvent({
    event: "recommendation.snoozed",
    owner: "backend",
    eventGroup: "recommendation",
    description: "A recommendation candidate was snoozed for a bounded period.",
    activityCode: "recommendation.snoozed",
    isRecommendationSignal: false,
    isAuthoritative: true,
    riskLevel: "low",
    allowedSources: ["backend"],
    privacyClass: "internal",
    requiredFields: ["workspaceId", "recommendationId", "snoozedUntil"],
  }),
] as const;

export const canonicalActivityMap = Object.freeze(
  Object.fromEntries(
    eventCatalog.map((definition) => [definition.event, definition.activityCode]),
  ) as Record<string, string>,
);

export const eventCatalogByName = Object.freeze(
  Object.fromEntries(
    eventCatalog.map((definition) => [definition.event, definition]),
  ) as Record<string, EventDefinition>,
);
