export const STAGE17_ALLOWED_PIECE_NAMES = [
  '@activepieces/piece-manual-trigger',
  '@activepieces/piece-webhook',
  '@activepieces/piece-schedule',
  '@activepieces/piece-http',
  '@activepieces/piece-code',
  '@activepieces/piece-delay',
  '@activepieces/piece-approval',
  '@activepieces/piece-csv',
  '@activepieces/piece-pdf',
  '@activepieces/piece-text-helper',
  '@activepieces/piece-file-helper',
  '@activepieces/piece-image-helper',
  '@activepieces/piece-sftp',
  '@activepieces/piece-smtp',
  '@activepieces/piece-rss',
  '@activepieces/piece-gmail',
  '@activepieces/piece-microsoft-outlook',
  '@activepieces/piece-microsoft-outlook-calendar',
  '@activepieces/piece-slack',
  '@activepieces/piece-microsoft-teams',
  '@activepieces/piece-telegram-bot',
  '@activepieces/piece-discord',
  '@activepieces/piece-google-sheets',
  '@activepieces/piece-google-drive',
  '@activepieces/piece-google-docs',
  '@activepieces/piece-google-calendar',
  '@activepieces/piece-github',
  '@activepieces/piece-gitlab',
  '@activepieces/piece-notion',
  '@activepieces/piece-airtable',
  '@activepieces/piece-trello',
  '@activepieces/piece-jira',
  '@activepieces/piece-linear',
  '@activepieces/piece-asana',
  '@activepieces/piece-clickup',
  '@activepieces/piece-hubspot',
  '@activepieces/piece-dropbox',
  '@activepieces/piece-microsoft-onedrive',
  '@activepieces/piece-microsoft-sharepoint',
  '@activepieces/piece-postgres',
  '@activepieces/piece-mysql',
  '@activepieces/piece-supabase',
  '@lexframe/piece-ai-gateway',
] as const;

export const STAGE17_PINNED_PIECE_NAMES = [
  '@activepieces/piece-manual-trigger',
  '@lexframe/piece-ai-gateway',
  '@activepieces/piece-http',
  '@activepieces/piece-webhook',
  '@activepieces/piece-google-sheets',
  '@activepieces/piece-slack',
] as const;

export const STAGE17_DIRECT_AI_PROVIDER_PIECES = [
  '@activepieces/piece-openai',
  '@activepieces/piece-anthropic',
  '@activepieces/piece-amazon-bedrock',
  '@activepieces/piece-azure-openai',
  '@activepieces/piece-cohere',
  '@activepieces/piece-cometapi',
  '@activepieces/piece-google-gemini',
  '@activepieces/piece-google-vertexai',
  '@activepieces/piece-grok-xai',
  '@activepieces/piece-mistral-ai',
  '@activepieces/piece-perplexity-ai',
  '@activepieces/piece-replicate',
] as const;

export const STAGE17_AUTOMATION_BRAND = {
  websiteName: 'Автоматизация',
  platformName: 'Рабочее пространство автоматизаций',
  primaryColor: '#6e40e3',
  logoIconUrl: '/lexframe-automation-icon.svg',
  fullLogoUrl: '/lexframe-automation-logo.svg',
  favIconUrl: '/lexframe-automation-icon.svg',
} as const;
