alter table if exists public.workspaces enable row level security;
alter table if exists public.workspace_members enable row level security;
alter table if exists public.permissions enable row level security;
alter table if exists public.profile_rules enable row level security;
alter table if exists public.profiles enable row level security;
alter table if exists public.automation_templates enable row level security;
alter table if exists public.installed_automations enable row level security;
alter table if exists public.installed_automation_versions enable row level security;
alter table if exists public.activepieces_projects enable row level security;
alter table if exists public.activepieces_flow_mappings enable row level security;
alter table if exists public.documents enable row level security;
alter table if exists public.document_artifacts enable row level security;
alter table if exists public.workflow_runs enable row level security;
alter table if exists public.run_steps enable row level security;
alter table if exists public.publication_requests enable row level security;
alter table if exists public.recommendations enable row level security;
alter table if exists public.audit_events enable row level security;

revoke all on public.workspaces from anon, authenticated;
revoke all on public.workspace_members from anon, authenticated;
revoke all on public.permissions from anon, authenticated;
revoke all on public.profile_rules from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.automation_templates from anon, authenticated;
revoke all on public.installed_automations from anon, authenticated;
revoke all on public.installed_automation_versions from anon, authenticated;
revoke all on public.activepieces_projects from anon, authenticated;
revoke all on public.activepieces_flow_mappings from anon, authenticated;
revoke all on public.documents from anon, authenticated;
revoke all on public.document_artifacts from anon, authenticated;
revoke all on public.workflow_runs from anon, authenticated;
revoke all on public.run_steps from anon, authenticated;
revoke all on public.publication_requests from anon, authenticated;
revoke all on public.recommendations from anon, authenticated;
revoke all on public.audit_events from anon, authenticated;
